# Generated by Django 4.1.1 on 2022-10-17 07:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=125)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('order_tax', models.FloatField()),
                ('discount', models.FloatField()),
                ('shipping', models.FloatField()),
                ('status', models.CharField(choices=[('recieved', 'Recieved'), ('ordered', 'Ordered'), ('pending', 'Pending')], default='recieved', max_length=20)),
                ('notes', models.TextField()),
                ('type', models.CharField(choices=[('new', 'New'), ('return', 'Return')], default='new', max_length=20)),
                ('products', models.ManyToManyField(to='inventory.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.supplier')),
            ],
        ),
    ]
