# Generated by Django 4.1.1 on 2022-10-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchase_discount_alter_purchase_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='products',
        ),
        migrations.AddField(
            model_name='purchase',
            name='products',
            field=models.ManyToManyField(to='purchases.purchaseitem'),
        ),
    ]
