# Generated by Django 4.1.2 on 2022-10-25 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hsn',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lot_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minimum_quantity',
        ),
    ]
