# Generated by Django 4.1.1 on 2022-10-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WoocommerceStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('consumer_key', models.CharField(max_length=128)),
                ('secret_key', models.CharField(max_length=128)),
            ],
        ),
    ]
