# Generated by Django 4.1.1 on 2022-10-17 07:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_date',
        ),
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='order_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sales.saleitem'),
        ),
        migrations.AddField(
            model_name='sale',
            name='shipping',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='type',
            field=models.CharField(choices=[('new', 'New'), ('return', 'Return')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('recieved', 'Recieved'), ('ordered', 'Ordered'), ('pending', 'Pending')], default='recieved', max_length=20),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
